language : bash
env:
    global:
      - HUB_PROTOCOL=https
      #GITHUB_TOKEN
      - secure: "11tWZh3LG4Iv5f/GnMctOzBOm3m1DAvYWdPwZBmj++gGAIAmptl9W9MX6XwkbTuaefs4QRB7WZ3EnFnJtqyrTDjd9Cfculyb7gX22a0vOsEnYQdtS9VWG9UpfeHHyhnIVhUD4I/uo/3nU3L4b93vLsuq6TT6xzZsM8BfqwOFdKSDbLcFPODqTe5WFlXAsXsGG8/AuPQmhgfG0ME/PTj1dzKArGcDPVmn8IaeGWvU5uRRBxA3X631F6yOSQlvhYdfINO861tKv6LhTOwbLQmy9QjH+tbfktN0Ykxe5UNIVWVqGR2/Aj/zRX83Jgdbl2dkpjOsY5ybITeIGXLnnEp0LjZ+dyC09PlB5oNgjZ1tNWm3EGADQryE/6MUj2LVAP+hwVZEcy5PLhKeSA29EUZjn+X/9AYO8x2w/ma6AJ5NrEV2Vz0Jg01LkVnzn2cF6ZLd1CxI1LjvjAHybBJEumMeZvmv2lZsiDGthknqIFSkVrHZjYQsMaAUrZm31Dmuiw5JPSjYvAPN0Ut6Z/1EfsPxd7ZtWNs6JR7gfyBpUcnkdcBhrPtTEB9ORRIGFzyiDmLesAU62KL68MWbvGkZcQJ3VtJHKDcBWA38ZKthOuqb/6DcYNginsWaW8J6VoZWk7eXyeDQ1sZpXqUTGjOlmnK+6DThzqfFwaqA/CK51f1P4LI="
branches:
  except:
  - nightly
git:
  quiet: true
before_install:
    - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    - sudo apt-get -qq update
    - sudo apt-get install -y debhelper devscripts fakeroot build-essential po-debconf gh
    - openssl aes-256-cbc -K $encrypted_efba3b7787e2_key -iv $encrypted_efba3b7787e2_iv -in 6D5E5753F12109663BABEED53087CD3324A99FBC.gpg.enc -out 6D5E5753F12109663BABEED53087CD3324A99FBC.gpg -d
    - gpg --import 6D5E5753F12109663BABEED53087CD3324A99FBC.gpg
install:
    - debuild '-k3087CD3324A99FBC'